---
# Please do not edit this file directly; it is auto generated.
# Instead, please edit 02-Geospatial-Lesson.md in _episodes_rmd/
title: "Ag Carpentry - Geospatial Data in different Ag file formats"
author: "Brittani"
date: "2019-10-19"
output: html_document
source: Rmd
---



####Motivating Questions:
- What are the common file types in agricultural data?
- What applications do I need to open these files?
- How can I make maps of my yield or application?

####Objectives with Spatial Data:
- Determine whether data are stored in vector or raster format
- Identify the coordinate system for a dataset
- Talk about when data don't have a projection defined (missing .prj file)
- Determine UTM zone of a dataset
- Reproject the dataset into UTM
- Import geospatial files into your R environment
- Visualize geospatial data with R
- Create geospatial files from lat/long coordinates
- Create an ab-line

####Keypoints:
- sf is prefereable for data analysis; it is easier to access the dataframe
- Projecting your data in utm is necessary for many of the geometric operations
you perform (e.g. making trial grids and splitting plots into subplot data)
- Different data formats that you are likely to encounter include gpkg, shp
(cpg, dbf, prj, sbn, sbx), geojson, and tif

### Setup

Below are the packages that we will use in this episode.



###Introducing Spatial Data with an Example Using Trial Design Data

####Read in the trial design

Use the function `read_sf()` to bring the dataset into your R environment.
Because we have already set the working directory for this file, we only need to
supply the file name. There are many functions for reading files into the
environment, but this function will create an object of class `sf`. This class
makes accessing spatial data much easier. Much like a data frame, you can access
variables within an `sf` object using the `$` operator, for example
`trial$DISTANCE`. For this and other reasons like the number of spatial
calculations available for `sf` objects, this class is perferred in most situations.


```r
trial <- read_sf("data/trialdesign.gpkg")
```

An `sf` object contains a geometry column. We can see the geometric points for
each polygon.
In geospatial terms, a polygon represents an area of land with distinct
boundaries represented by a series of points.


```r
head(trial$geom)
```

```
## Geometry set for 6 features 
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: -81.97862 ymin: 41.74608 xmax: -81.97743 ymax: 41.74659
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
## First 5 geometries:
```

```
## POLYGON ((-81.97853 41.74656, -81.97853 41.7463...
```

```
## POLYGON ((-81.97832 41.74657, -81.9783 41.74608...
```

```
## POLYGON ((-81.9781 41.74659, -81.97808 41.74609...
```

```
## POLYGON ((-81.97788 41.74658, -81.97787 41.7460...
```

```
## POLYGON ((-81.97767 41.74658, -81.97765 41.7460...
```

####Check the coordinate reference system

Geospatial data has a coordinate reference system (CRS) that projects the map in
a specific location.
**Explain projection more in layman's terms here**

**Start of layman's terms section - Dena:**
####What is a projection?

A projection is a way of making the earth's curved surface fit into something you 
can represent on a flat computer screen. To understand why that matters, take a look
at the difference between [the Mercator projection](https://en.wikipedia.org/wiki/Mercator_projection#/media/File:Mercator_projection_Square.JPG) of the world and the 
[Boggs eumorphic projection](https://en.wikipedia.org/wiki/Boggs_eumorphic_projection#/media/File:Boggs_eumorphic_projection_SW.JPG)

In the Mercator projection, space that doesn't exist is created to make a "flat" map 
and Greenland and Antarctica disproportionately huge. In the Boggs projection, strategic 
slices are cut out of the ocean so that the sizes appear a bit closer to true, but Canada 
and Russia get pinched and Greenland gets bisected. There will always be some compromises 
made in a projection system that converts curved surfaces to flat ones for the same reason 
that it's difficult to make an orange peel lie flat. So the method you select will have an 
effect on your outcome.
**End of layman's terms section - Dena**



Different CRSs use different projections of the earth into
2-dimensional space. Some coordinate reference systems, such as UTM zones, are
measured in meters from a reference point in the zone. Latitude and longitude
represent a different type of CRS, defined in terms of angles across a sphere.
Before combining files
and performing operations on a file, it is important to check the CRS. The
function for this is `st_crs().`


```r
st_crs(trial)
```

```
## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```

The trial design is in lat/long. If we want to create measures of distance,
we need the trial design in UTM. First, we must determine the UTM zone of the
trial area. 

####Calculate the UTM zone from the longitude

The UTM system divides the surface of Earth between 80°S and 84°N latitude into
60 zones, each 6° of longitude in width. Zone 1 covers longitude 180° to 174° W;
zone numbering increases eastward to zone 60 that covers longitude 174 to 180
East. The following code takes a longitude point and determines its UTM zone.
`long2UTM()` is a function written to take the argument `long` and output the
result of the equation. `floor()` returns the largest integer that is not
greater than the input.  The `st_bbox()` function returns the bounding box of
the dataset, i.e. the four corners defining a rectangle that would contain all
of the polygons.  By taking the mean of the first and third items returned by
`st_bbox()`, we get the longitude of the point directly in the center of the box.


```r
long2UTM <- function(long){
  utm <- (floor((long + 180)/6) %% 60) + 1
  return(utm)
}

utmzone <- long2UTM(mean(st_bbox(trial)[c(1,3)]))
utmzone
```

```
## [1] 17
```

We can see that -81.975805 corresponds to UTM zone
17.

####Projection for UTM

**Dena's comprehension check here: The way to recognize the difference between 
UTM and WGS584 is whether some data or piece of code starts with 326 or 4326? From
reading what's here, it gives me the impression that that's more of
an external thing than something you'd see in the file/data? How do you know which one
you're looking at if you don't already know? I'd like to brainstorm on a way to make this
section a little easier to understand without doing damage to accuracy.**

Using the UTM zone we calculated above, we now need the full ESPG code to
transform the file to the new CRS. EPSG Geodetic Parameter Dataset is a public
registry of spatial reference systems, Earth ellipsoids, coordinate
transformations and related units of measurement. The ESPG is one way to assign
or transform the CRS in R. The ESPG for UTM always begins with "326" and the
last numbers are the number of the zone. The code below pastes together the full
ESPG code for any `utmzone` we calculate with `long2UTM`. `paste0()` pastes
together the two arguments `"326"` and `utmzone` as string. But when we transform
`trial` into UTM, we only need the ESPG number. So we convert that to numeric with
`as.numeric()`, giving us a final ESPG of 32617.


```r
projutm <- as.numeric(paste0("326", utmzone))
projutm
```

```
## [1] 32617
```

All modern latitude and longitude coordinates use a standard called WGS84.  The ESPG 
for WGS84 is 4326. This is the projection your equipment reads, so any trial design 
files will need to be transformed back into WGS84 before you implement the trial. Also, 
all files from your machinery, such as yield, as-applied, and as-planted, will be 
reported in latitude and longitude.

**Dena: What differences do you see in the data itself to recognize whether you're looking at
WGS84 or UTM in order to know which code you need to use in the transformation?**

####Transform the projection of file

To transform the trial design file into UTM, use `st_transform` and the crs
object `projutm`.


```r
trialutm <- st_transform(trial, projutm)
```

**Exercise**
1. Bring the file called "hord_f98_asplanted_2017.shp" in your environment. Name
the object `planting`. This file contains the planting information for 2017.
2. Identify the CRS of the object. **Dena: So far I haven't seen anything that would help them understand how to do this, unless 326 or 4326 appear somewhere in code or data we haven't shown them in text yet? Or else I've missed something key that it may help to add in.**
3. Look at the geometry features. What kind of geometric features are in this dataset?
4. Transform the file to UTM or Lat/Long, depending on the current CRS.

**Solution**

<<<<<<< HEAD

```r
planting <- read_sf("data/asplanted.gpkg")

st_crs(planting)
```

```
## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```

```r
planting$geom
```

```
## Geometry set for 6382 features 
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -81.97843 ymin: 41.73952 xmax: -81.97315 ymax: 41.74653
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
## First 5 geometries:
```

```
## POINT (-81.97829 41.73953)
```

```
## POINT (-81.97828 41.73953)
## POINT (-81.97828 41.73953)
```

```
## POINT (-81.97827 41.73953)
```

```
## POINT (-81.97825 41.73953)
```

```r
planting_latlong <- st_transform(planting, 4326)

st_crs(planting_latlong)
```

```
## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```
**Dena - It looks like this section needs a conflict resolved, this is an unresolved Git conflict marker**
<<<<<<< HEAD
The cleaned planting file was in UTM initially. The zone is 17 which is to be expected 
as it is from the same field as the trial design file we worked with earlier. When we
look at the geometry features, they are 6,277 points defined in x and y coordinates.
Using the ESPG for lat/long we covered earlier 4326, we create a new file called
`planting_latlong` with the CRS of WGS84.


```r
trialutm <- st_transform(trial, projutm)
```
=======
The cleaned planting file was in UTM initially. The zone is 17 which is to be 
expected as it is from the same field as the trial design file we worked with earlier. 
When we look at the geometry features, they are 6382 points defined in x 
and y coordinates. Using the ESPG for lat/long we covered earlier 4326, we create a new
file called `planting_latlong` with the CRS of WGS84.
>>>>>>> ac5d8087dfe7ad986d1cc9650fbf13b934ca5f96

####Save the file 

Use `st_write()` to save an sf object. If you do not specify a directory, the working 
directory will be used. We include the object we are saving `trialutm` and the name 
we would like to give the saved file `"trial.gpkg"`. Additionally, we specify the
`layer_options` and `update` values to enable overwriting an existing file with the same name. 

You can save the file as a .gpkg or .shp file. The advantage of a .gpkg file is
that you only save one file rather than four files in a shapefile. Because
shapefiles contain multiple files, they can be corrupted if one piece is missing.
One example is a .prj file. In this case, the shapefile will have no CRS, and
you will need to determine the CRS of the object. You will often need to transform a 
file from UTM to lat/long and save the new file during trial design, so this is an important step.


```r
st_write(trialutm, "trial_utm.gpkg", layer_options = 'OVERWRITE=YES', update = TRUE)
```

```
## Updating layer `trial_utm' to data source `trial_utm.gpkg' using driver `GPKG'
## options:        OVERWRITE=YES 
## Updating existing layer trial_utm
## Writing 257 features with 10 fields and geometry type Polygon.
```

The new .gpkg file will be visible in your working directory. One common problem
with these files is that when you try to open a .gpkg file for the first time in
R, it might not work if you haven't opened it in QGIS before.
**Dena: Any idea why this is? During Thursday's meeting, we weren't sure if we were going to get into
QGIS. If this is something that is critical, we should make sure to get QGIS available.**

####Visualize the trial map

We often want to visualize the contents of geospatial files. When we design a trial, 
we need to see the resulting applications. With yield data, we look for spatial patterns 
in the field, where is the yield higher or more varied. Before making a map, we need to
know what variables are in the trial dataset.
Use `names()` to view the different variables in `trialutm`. Say we want to make a
map of the nitrogen rates. We need to identify the variable name for the target
nitrogen.



```r
names(trialutm)
```

```
##  [1] "GRIDID"     "GRIDX"      "GRIDY"      "DISTANCE"   "TREATMENT" 
##  [6] "BLOCK"      "RANDNBR"    "treat_type" "NRATE"      "SEEDRATE"  
## [11] "geom"
```


In `trialutm` there are 11 variables, but the variables we might want to map are
`NRATE` and `SEEDRATE`. The following map is created with functions from a package 
called `tmap`. We are using `tm_polygon()`
fill the polygons with a color based on the variable `NRATE` inside the object
`trialutm `. For a different kind of geospatial data such as points, we need to use
`tm_dots()` or `tm_squares()`. `tmap` provides many options for displaying data, 
including text markers on the map. Text labels might be good for making a map of 
several land parcels with their names as the label. We use other arguments in the
code below to choose the position of the map
legend, title of the variable, size of text, and width of legend.



```r
tm_shape(trialutm) + tm_polygons('NRATE', title = "Nitrogen Rate") +
  tm_layout(legend.outside = TRUE, frame = FALSE) +
  tm_legend(text.size = 1,
            title.size = 1,
            width = 100,
            bg.color = "white")
```

![plot of chunk map](figure/map-1.png)


####Creating Spatial Objects

You may also have the coordinates of a spatial object but not a spatial file.
One example is a boundary file or AB-line for your field. We will use the
AB-line and boundary files later when designing the trials. But for this
example, they are good for displaying how to create a spatial object from
coordinates. 

####AB-line File (reading it in or creating it)

Some of you may have a shapefile of your ab-line, but most of you will have the
two endpoints. This is all you need to make a geospatial object for your ab_line 
in R. First, we define the latitude and longitude of the two points. We will call
these point A and point B.


```r
LongA <- -82.97452
LatA <- 40.73862

LongB <- -82.97452
LatB <- 40.74480
```

`st_linestring()` creates an object of class sf from a matrix.
`rbind(c(LongA, LatA), c(LongB, LatB))` creates a matrix with two rows, one for point A and
one for point B. This object is then piped into the function `st_linestring()` to create 
the `sf` object. Finally, using `st_sf()` and  `st_sfc()` we create a simple feature geometry 
column from the set of geometries in `ab_string`. 


```r
ab_string <- rbind(c(LongA, LatA), c(LongB, LatB)) %>% st_linestring() 
ab_line <-st_sf(id = 'ab_line', st_sfc(ab_string))
```

Now we must assign the CRS of the line. We know that the coordinates were taken
from an object in WGS84, **Dena - How do we know that?** so we can assign the same 
CRS with `st_crs` and typing
out the correct `crs`. Another way we can do this is by using `crs()`. This
second method is preferred to avoid mistakes when remembering the UTM zone of
multiple files. **Dena: If the second method is preferred, then let's not introduce
the first method, so that the instructions they see lead them to do the right thing.**


```r
st_crs(ab_line) <- st_crs(trial)
st_crs(ab_line)
```

```
## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```

```r
st_write(ab_line,"abline.gpkg", layer_options = 'OVERWRITE=YES', update = TRUE)
```

```
## Updating layer `abline' to data source `abline.gpkg' using driver `GPKG'
## options:        OVERWRITE=YES 
## Updating existing layer abline
## Writing 1 features with 1 fields and geometry type Line String.
```

Plot the resulting AB-line with the generic plotting function for `sf` objects.


```r
plot(ab_line)
```

![plot of chunk plotabline](figure/plotabline-1.png)

####Reading in the Boundary File

We will read in the boundary file and plot the boundary file with the abline to see 
how the farmer drives across the field. 


```r
boundary <- read_sf("data/boundary.gpkg")
st_crs(boundary)
```

```
## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```

After plotting `boundary`, we plot `ab_line` with `add = TRUE` which adds the new 
plot over the existing plot of the field boundary. We see that the farmer drives 
across the longest part of the field, beginning on the right-hand side. 


```r
plot(boundary$geom)
plot(ab_line, add = TRUE)
```

![plot of chunk plotboth](figure/plotboth-1.png)
