---
# Please do not edit this file directly; it is auto generated.
# Instead, please edit 03-Geospatial-Lesson.md in _episodes_rmd/
title: "Geospatial Data and SSURGO"
output: html_document
source: Rmd
---




#### Motivating Questions:
- What are the common file types in agricultural data?
- What applications do I need to open these files?
- How can I make maps of my yield or application?

#### Objectives with Spatial Data:
- Determine whether data are stored in vector or raster format
- Identify the coordinate system for a dataset
- Talk about when data don't have a projection defined (missing .prj file)
- Determine UTM zone of a dataset
- Reproject the dataset into UTM
- Import geospatial files into your R environment
- Visualize geospatial data with R
- Create geospatial files from lat/long coordinates
- Create an ab-line

#### Keypoints:
- sf is prefereable for data analysis; it is easier to access the dataframe
- Projecting your data in utm is necessary for many of the geometric operations
you perform (e.g. making trial grids and splitting plots into subplot data)
- Different data formats that you are likely to encounter include gpkg, shp
(cpg, dbf, prj, sbn, sbx), geojson, and tif

### Setup

Below are the packages that we will use in this episode.



###Introducing Spatial Data with SSURGO data

####What is a CRS?

Geospatial data has a coordinate reference system (CRS) that reports how the map is projected and what point is used as a reference. A projection is a way of making the earth's curved surface fit into something you 
can represent on a flat computer screen. The point used for reference during projection is called a datum.

## Importance of Projections
To understand why projection matters, take a look
at the difference between [the Mercator projection](https://en.wikipedia.org/wiki/Mercator_projection#/media/File:Mercator_projection_Square.JPG) of the world and the 
[Boggs eumorphic projection](https://en.wikipedia.org/wiki/Boggs_eumorphic_projection#/media/File:Boggs_eumorphic_projection_SW.JPG)

In the Mercator projection, space that doesn't exist is created to make a "flat" map 
and Greenland and Antarctica disproportionately huge. In the Boggs projection, strategic 
slices are cut out of the ocean so that the sizes appear a bit closer to true, but Canada 
and Russia get pinched and Greenland gets bisected. There will always be some compromises 
made in a projection system that converts curved surfaces to flat ones for the same reason 
that it's difficult to make an orange peel lie flat. So the method you select will have an 
effect on your outcome.

####Reading in the Boundary File

Before we can look at a CRS in R, we need to have a geospatial file in the R environment. We will bring in the field boundary. Use the function `read_sf()` to bring the dataset into your R environment.
Because we have already set the working directory for this file, we only need to
supply the file name. 


```r
boundary <- read_sf("data/boundary.gpkg")
```

There are many functions for reading files into the
environment, but `read_sf()` creates an object of class `sf` or simple feature. This class
makes accessing spatial data much easier. Much like a data frame, you can access
variables within an `sf` object using the `$` operator. For this and other reasons like the number of spatial
calculations available for `sf` objects, this class is perferred in most situations.

####Check the coordinate reference system

The function for retreiving the CRS of a simple feature is `st_crs().` Generally it is good practice to know the CRS of your files, but before combining files and performing operations on geospatial data, it is particularly important. Some commands will not work if the data is in the wrong CRS or if two dataframes are in different CRSs.


```r
st_crs(boundary)
```

```
## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```
The boundary file is projected in longitude and latitude using the WGS84 datum. This will be CRS of most of the data you see. 


Sometimes when looking at a shapefile, the .prj file can be lost. Then `st_crs()` will return empty, but `sf` objects contain a geometry column. We can see the geometric points for the vertices of
each polygon or the points in the data.


```r
head(boundary$geom)
```

```
## Geometry set for 6 features 
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -81.97853 ymin: 41.73949 xmax: -81.97306 ymax: 41.7466
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
## First 5 geometries:
```

```
## MULTIPOLYGON (((-81.97319 41.74574, -81.97385 4...
```

```
## MULTIPOLYGON (((-81.97805 41.74098, -81.97803 4...
```

```
## MULTIPOLYGON (((-81.9741 41.73985, -81.97306 41...
```

```
## MULTIPOLYGON (((-81.97807 41.74157, -81.97806 4...
```

```
## MULTIPOLYGON (((-81.97817 41.74612, -81.97807 4...
```

The trial design is in lat/long using WGS84. 

## UTM Zones

Some coordinate reference systems, such as UTM zones, are measured in meters. Latitude and longitude represent a different type of CRS, defined in terms of angles across a sphere. If we want to create measures of distance, we need the trial design in UTM. But there are many UTM zones, so we must determine the zone of the trial area. 

The UTM system divides the surface of Earth between 80°S and 84°N latitude into
60 zones, each 6° of longitude in width. Zone 1 covers longitude 180° to 174° W;
zone numbering increases eastward to zone 60 that covers longitude 174 to 180
East. 

####st_transform and ESPG Codes

For reprojecting spatial data, the function `st_transform()` uses an ESPG code to transform a simple feature to the new CRS. EPSG Geodetic Parameter Dataset is a public registry of spatial reference systems, Earth ellipsoids, coordinate transformations and related units of measurement. The ESPG is one way to assign or transform the CRS in R. 

The ESPG for UTM always begins with "326" and the last numbers are the number of the zone. The ESPG for WGS84 is 4326. This is the projection your equipment reads, so any trial design  files will need to be transformed back into WGS84 before you implement the trial. Also, all files from your machinery, such as yield, as-applied, and as-planted, will be reported in latitude and longitude with WGS84.

####Transforming

The function `st_transform_utm()` transforms a simple feature into a new CRS. This function is in the functions.R script, and is described there.

```r
boundaryutm <- st_transform_utm(boundary)
st_crs(boundaryutm)
```

```
## Coordinate Reference System:
##   EPSG: 32617 
##   proj4string: "+proj=utm +zone=17 +datum=WGS84 +units=m +no_defs"
```

**Exercise**
1. Bring the file called "asplanted.gpkg" in your environment. Name
the object `planting`. This file contains the planting information for 2017.
2. Identify the CRS of the object. 
3. Look at the geometry features. What kind of geometric features are in this dataset?
4. Transform the file to UTM or Lat/Long, depending on the current CRS.

**Solution**


```r
planting <- read_sf("data/asplanted.gpkg")

st_crs(planting)
```

```
## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```

```r
planting$geom
```

```
## Geometry set for 6382 features 
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -81.97843 ymin: 41.73952 xmax: -81.97315 ymax: 41.74653
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
## First 5 geometries:
```

```
## POINT (-81.97829 41.73953)
```

```
## POINT (-81.97828 41.73953)
## POINT (-81.97828 41.73953)
```

```
## POINT (-81.97827 41.73953)
```

```
## POINT (-81.97825 41.73953)
```

```r
plantingutm <- st_transform_utm(planting)

st_crs(plantingutm)
```

```
## Coordinate Reference System:
##   EPSG: 32617 
##   proj4string: "+proj=utm +zone=17 +datum=WGS84 +units=m +no_defs"
```

The cleaned planting file was in WGS84 initially. When we look at the geometry features, they are 6382 points defined in xand y coordinates. Using `st_transform_utm()` we create a new file called `plantingutm` with the CRS of UTM zone 17.

####Save the file 

Use `st_write()` to save an sf object. If you do not specify a directory, the working 
directory will be used. We include the object we are saving `boundaryutm` and the name 
we would like to give the saved file `"boundary_utm.gpkg"`. Additionally, we specify the
`layer_options` and `update` values to enable overwriting an existing file with the same name. 

You can save the file as a .gpkg or .shp file. The advantage of a .gpkg file is
that you only save one file rather than four files in a shapefile. Because
shapefiles contain multiple files, they can be corrupted if one piece is missing.
One example is a .prj file. In this case, the shapefile will have no CRS, and
you will need to determine the CRS of the object. You will often need to transform a 
file from UTM to lat/long and save the new file during trial design, so this is an important step.


```r
st_write(boundaryutm, "boundary_utm.gpkg", layer_options = 'OVERWRITE=YES', update = TRUE)
```

```
## Updating layer `boundary_utm' to data source `boundary_utm.gpkg' using driver `GPKG'
## options:        OVERWRITE=YES 
## Updating existing layer boundary_utm
## Writing 10 features with 1 fields and geometry type Multi Polygon.
```

The new .gpkg file will be visible in your working directory. One common problem
with these files is that when you try to open a .gpkg file for the first time in
R, it might not work if you haven't opened it in QGIS before.

####Visualizing the data

There are several ways to visualize spatial data. First, we can use `plot()` to look at the basic shape of the data. 


```r
plot(boundary$geom)
```

![plot of chunk unnamed-chunk-2](../figure/unnamed-chunk-2-1.png)

We can also plot the data where the polygons change color based on the value of one of the variables. This can be done with a package `tmap()`. We will discuss this package more in the next lesson, but we provide the function `map_poly()` in the functions.R script for making a simple map with polygon features colored based on a given variable. The function requires a spatial object and a variable name in ''.


```r
map_poly(boundary, 'Type', 'Part of Field')
```

![plot of chunk unnamed-chunk-3](../figure/unnamed-chunk-3-1.png)

#SSURGO Soil Data

The SSURGO data is probably a dataset you are familiar with already. You can obtain a soil
description of your field on the Web Soil Survey website below. The SSURGO dataset has been
developed over a century of surveying land and analyzing soil samples across the United States.
While the website is one way to access the soil data, R also has a package called `FedData` 
that has a function `get_ssurgo()` for accessing the soil data in the R environment. 

https://websoilsurvey.sc.egov.usda.gov/App/WebSoilSurvey.aspx

The next line brings the SSURGO data into the R environment with the name `ssurgo` and the  object `boundary` from the geospatial lesson. Note here that the class of `boundary` needs  to be `spatial` rather than `sf`, so we transform the object with `as(boundary,"Spatial")`.


```r
boundarynew <- read_sf("data/asplanted.gpkg")
boundary <- subset(boundary, Type == "Trial")
boundary.sp <- as(boundary, "Spatial")
lwgeom::st_make_valid(boundary)
```

```
## Simple feature collection with 2 features and 1 field
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -81.97817 ymin: 41.73981 xmax: -81.97327 ymax: 41.74615
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
## # A tibble: 2 x 2
##   Type                                                                      geom
##   <chr>                                                       <MULTIPOLYGON [°]>
## 1 Trial (((-81.97803 41.73981, -81.97805 41.74098, -81.97683 41.74091, -81.9759…
## 2 Trial (((-81.97339 41.74573, -81.97327 41.73986, -81.9741 41.73985, -81.97412…
```

```r
plot(boundary.sp)
```

![plot of chunk ssurgo](../figure/ssurgo-1.png)

```r
ssurgo <- get_ssurgo(boundary.sp, "samplefield")
```

```
## Error in {: task 1 failed - "Download of https://sdmdataaccess.nrcs.usda.gov/Spatial/SDMNAD83Geographic.wfs?Service=WFS&Version=1.0.0&Request=GetFeature&Typename=SurveyAreaPoly&BBOX=-81.978165150311,41.7398141866265,-81.9732655092103,41.7461469570485 failed!"
```

The downloaded `ssurgo` is a list with 2 objects, `spatial` and `tabular`. The `spatial` 
object contains the polygons of soil types for the field, and  `tabular` contains many 
dataframes with attributes collected for the soil and soil horizons. Note that these dataframes 
and their relationships with one another ar very complex. To use these data, you must carefully 
read the SSURGO documentation. Merging the dataframes to have one value of the attributes for 
each soil polygon requires reducing the dimension of the data, often by weighting the attributes
by horizon depth.

Let's make a map of the soil types on this field. First, we need to locate the part of
`tabular` with the soil names; these can be found in `muaggatt`.


```r
names <- ssurgo$tabular$muaggatt 
```

```
## Error in eval(expr, envir, enclos): object 'ssurgo' not found
```

*Exercise 4*: What are the soil types present on the field as seen in `names`? Are the soil 
defined by anything other than the soil type?

*Exercise 4 Solution*


```r
names
```

```
## function (x)  .Primitive("names")
```

Looking at `names` we can see there are eight types of soil on the field, and the dataframe 
reports areas with different slopes with different names. We often know the slope of the field, 
and so we may want to combine areas of the field with the same soil type and different slopes.

We need one dataframe with both the soil name and spatial data. We will merge the soil data 
and the spatial data by the `musym`. Note that in one of the dataframes the variable is 
capitalized and not in the other. We must rename the variable for consistency using `rename()` from `dplyr`.


```r
spatial <- as(ssurgo$spatial, "sf")
```

```
## Error in .class1(object): object 'ssurgo' not found
```

```r
spatial <- dplyr::rename(spatial, musym = MUSYM)
```

```
## Error in dplyr::rename(spatial, musym = MUSYM): object 'spatial' not found
```

```r
spatial <- merge(spatial, names, by = "musym")
```

```
## Error in merge(spatial, names, by = "musym"): object 'spatial' not found
```

```r
head(spatial$muname)
```

```
## Error in head(spatial$muname): object 'spatial' not found
```

*Exercise 5*: Create the Soil Map

Use `map_poly()` to make a map where the polygon color is informed by the soil names in
`muname`. 


*Exercise 5 Solution*


```r
map_soil <- map_poly(spatial, 'muname', "Soil Type")
```

```
## Error in as.list.environment(environment()): object 'spatial' not found
```

```r
map_soil
```

```
## Error in eval(expr, envir, enclos): object 'map_soil' not found
```

The map shows that there are quite a few soil types on the field, and several show up
in different sections of the field. However, most of the soils are silt loam. It might 
be difficult to understand the different soils without more information about soil weathering 
and texture. This is also provided within SSURGO and is likely something you know about in 
your own field. 

# Example with your own field

Here we are going to download the SSURGO maps for your own field using your boundary file if you have one. Then, For an example of how this is done with clay, silt, and sand content, contact 
the workshop instructors. 


```r
soil_content <- c_s_s_soil(ssurgo = ssurgo)
```

```
## Error in c_s_s_soil(ssurgo = ssurgo): object 'ssurgo' not found
```
