Welcome to Data Harvesting for Agriculture!

Our motivation for creating this workshop is the recent, rapid increase in the volume of data produced on farms and the use of such data for decision making by farmers.  We don't expect to replace the data analysis services that are currently provided by the Ag Tech industry, but we do want to arm you with knowledge to help you better communicate with those service providers.  Moreover, we believe that your data will be more valuable to you if you have some ability to analyze it yourself, regardless of whether you continue to do business with a particular company years in the future.  

After attending our workshop, you will be able to develop small computer programs of your own for analysis, visualization, and decision making, and will be able to share those programs with others.

Don't worry -- we're not asking you to develop research software from scratch! We'll be providing you with scripts and programs that will perform most of the work for you. However, helping you understand the way the software works will let you run different scenarios for yourself and decide among several alternatives for your business.

# What you'll learn

By the end of this workshop, you will know more about:
* How to understand more about the data coming from your agricultural equipment
* What you can do with it yourself using free and open source tools
* Where to find historical data relevant to your own farm and/or county's location and land
* How to use both current and historical data about your own farm and/or county to develop custom fertilizing strategies 
that can improve cost effective application in your particular location

To do this, we'll be introducing you to:
* RStudio, free and open source software used for creating both programs and visualizations
* Geospatial data types that you may encounter, how to tell them apart, and how to use them for your own location
* Commonly used file formats that your agricultural equipment may provide, how to tell them apart, and how to know what to do with each of them
* Basic data cleaning processses so that you'll get more useful and effective results from analysis of your farm's or your region's data
* Ways to calculate the most cost-effective application rates and assess the effectiveness of the results
* How to design a custom set of variable application rates for your own farm, apply them, and analyze the results consistently across multiple years
 
# What to bring
While our lessons are taught with sample data so that everyone can follow along with the same set of numbers and values and check their results, you can get additional benefits from this workshop if you bring along some data that's relevant to your own farm.

Here's what to bring to this workshop:
* A laptop (Windows, Mac, or Linux)
* Past yield maps
* A boundary file for the areas you'd like to analyze
* Machinery widths (if you have them; if not, we can estimate)
* Any prescription maps you use for your fields
* (If you already do variable rate application) Past application maps
* A-B line or guidance line information

# Getting connected to the campus network as a guest

The IllinoisNet_Guest network allows University visitors to access the wireless network.

1. Connect to the IllinoisNet_Guest network.
2. Visit http://illinois.edu and you'll be redirected to the guest network portal.
3. Don't use the NetID login section; that's for University employees. Instead, click the guest link at the bottom of the page.
4. Follow the "Click Here for Wi-Fi Access" prompt.
5. Follow the prompts to provide the information to create a guest account.
6. When you're redirected to the illinois.edu home page, you've completed the process.

Guest access is granted one day at a time; for the next day, you'll need to log in to IllinoisNet_Guest again.

# Some workshop guidelines
We'll have instructors and helpers available throughout the day to help you get over any hurdles if you get stuck. 

We'll use two colors of sticky notes for quick check-ins around the room to see if everyone's caught up or needs help. If you'd like to signal for a helper, put the "help" sticky note on the corner of your laptop screen and we'll come to assist.
