library(sf)
library(fasterize)
library(gstat)
library(raster)
library(rjson)
library(httr)
library(rgdal)
library(rgeos)
library(maptools)
library(knitr)
library(tmap)
library(ggplot2)
library(gridExtra)
library(grid)
library(FedData)
library(plyr)

source('/Users/jillnaiman/trial-lesson_ag/_episodes_rmd/functions.R')
plot(c(1,2,3), c(1,2,3))
