library(sf)
library(fasterize)
library(gstat)
library(raster)
library(rjson)
library(httr)
library(rgdal)
library(rgeos)
library(maptools)
library(knitr)
library(tmap)
library(ggplot2)
library(gridExtra)
library(grid)
library(FedData)
library(plyr)

source('./functions.R')

#boundary <- read_sf("data/boundary_transformed.gpkg")
